@EnergomerWebApp_HostAddress = http://localhost:5202

GET {{EnergomerWebApp_HostAddress}}/Field/GetFields
Accept: application/json

###

GET {{EnergomerWebApp_HostAddress}}/Field/PointInsideFields/41.3380610642585&45.6962567581079
Accept: application/json
